---
repo_url: https://github.com/jonh-carvalho/PFE_25.2_8001_I
site_author: ProjetoX
site_name: PFE_25.2_8001_I
copyright: Copyright ©️ 2025, ProjetoX / 2025, ProjetoX

extra_css:
  - css/extra.css

markdown_extensions:
  # Tooltips
  - abbr
  # Admonitions
  - admonition
  # Annotations, Buttons, Grids, Icons & Emojis, Images, Tooltips
  - attr_list
  # Footnotes
  - footnotes
  # Annotations, Grids, Images
  - md_in_html
  # Images
  - pymdownx.blocks.caption
  # Formatting
  - pymdownx.caret
  # Formatting
  - pymdownx.critic
  # Admonitions
  - pymdownx.details
  # Icons & Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  # Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # Code Blocks
  - pymdownx.inlinehilite
  # Formatting
  - pymdownx.keys
  # Formatting
  - pymdownx.mark
  # Code Blocks, Tooltips
  - pymdownx.snippets
  # Admonitions, Annotations, Code Blocks, Content Tabs
  - pymdownx.superfences
  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Lists
  - pymdownx.tasklist:
      custom_checkbox: true
  # Formatting
  - pymdownx.tilde
  # Data Tables
  - tables
  - toc:
      permalink: true

plugins:
  - minify:
      minify_html: true
  - search

theme:
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    logo: simple/react
    favicon: simple/react
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

#nav: 
 # - Home: index.md
  #- Disciplina:
   #   -  Aulas: Disciplina/Aulas.md
    #  -  Github: github.md
     # -  Mkdocs: mkdocs.md
      #-  CodeSpace: Codespace.md 
  #- React: 
   #   -  Introdução: React/01_Intro.md
    #  -  Componentes: React/Componentes.md
     # -  Hooks: React/Hooks.md
      #-  Context API: React/ContextAPI.md
      #-  React Router: React/ReactRouter.md

      #-  Redux: React/Redux.md
