name: Deploy to GitHub Pages

# Executa este fluxo sempre que houver um push na branch 'main'
on:
  push:
    branches:
      - main # ou master, dependendo do nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # 3. Instala as dependências (MkDocs e plugins)
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      # 4. Executa o build do site
      - name: Build site
        run: mkdocs build

      # 5. Publica o site no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site